version: '3'

services:
  crossfit-diary-db-service:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crossfit_diary
    ports:
      - "5432:5432"
    # volumes:
    #   - './init-scripts:/docker-entrypoint-initdb.d'

  wod-data-collect-service:
    build: ./wod-data-collect-service
    volumes:
      - ./wod-data-collect-service:/usr/src/app
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - crossfit-diary-db-service
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: crossfit_diary
      PGPORT: 5432
      PGHOST: crossfit-diary-db-service
