version: '3'

services:
  crossfit-diary-db-service:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crossfit_diary
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  wod-data-collect-service:
    build: ./wod-data-collect-service
    volumes:
      - ./wod-data-collect-service:/usr/src/app
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - crossfit-diary-db-service
      - kafka
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: crossfit_diary
      PGPORT: 5432
      PGHOST: crossfit-diary-db-service

  workouts-data-transform-service:
    build: ./workouts-data-transform-service
    volumes:
      - ./workouts-data-transform-service:/usr/src/app
    depends_on:
      - kafka
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: crossfit_diary
      PGPORT: 5432
      PGHOST: crossfit-diary-db-service

  crossfit-diary-frontend:
    build: ./crossfit-diary-frontend
    volumes:
      - ./crossfit-diary-frontend:/usr/src/app
    ports:
      - "3100:3100"
    depends_on:
      - wod-data-collect-service

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "7203:7203"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

volumes:
  pgdata:
